# Welcome to Jekyll!

# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Haoran Ma"
title_separator: "-"
name: &name "Haoran Ma"
description: &description "M.S. student at the University of Science and Technology of China (USTC)"
url: "https://haoran-ma.github.io"
baseurl: ""
repository: "HaoRan-Ma/HaoRan-Ma.github.io"

# Site Author
author:
  avatar: "meprofile.png"
  name: "Haoran Ma"
  bio: "M.S. student at USTC, University of Science and Technology of China."
  location: "Suzhou, China"
  employer: "University of Science and Technology of China (USTC)"
  email: "haoranma@mail.ustc.edu.cn"

  # Academic websites
  googlescholar: "https://scholar.google.com/citations?user=jHgbLQcAAAAJ"

  # Repositories
  github: "HaoRan-Ma"

# Publication Categories
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# Site Settings
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# Feed
atom_feed:
  hide: false

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:
  - ".bundle"
  - ".sass-cache"
  - ".jekyll-assets-cache"
  - ".github"
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README
  - Dockerfile
  - tmp

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown Processing
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections
collections:
  teaching:
    output: true
    permalink: /teaching/:path/
  publications:
    output: true
    permalink: /publications/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/
  talks:
    output: true
    permalink: /talks/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Output
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
